version: "3.9"

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_START_RPC=true
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5

  node-app:
    build: .
    container_name: movie-ticket-api
    ports:
      - "3000:3000"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_KEYSPACE=ticketkeyspace
      - PORT=3000
    volumes:
      - .:/app
    command: npm start
